# Generated by Django 4.2.7 on 2026-03-14 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '1026_remove_inventory_calculation'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerchallanmaster',
            name='sale_free_qty',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='purchasemaster',
            name='product_free_qty',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='returnpurchasemaster',
            name='returnproduct_free_qty',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='returnsalesmaster',
            name='return_sale_free_qty',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='salesmaster',
            name='sale_free_qty',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='supplierchallanmaster',
            name='product_free_qty',
            field=models.FloatField(default=0.0),
        ),
    ]
