# Generated by Django 4.2.7 on 2026-03-14 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_free_qty_to_challanmaster2'),
        ('core', '1027_customerchallanmaster_sale_free_qty_and_more'),
    ]

    operations = [
    ]
