# Generated by Django 5.2.6 on 2026-03-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '1027_alter_web_user_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasemaster',
            name='product_free_qty',
            field=models.FloatField(default=0.0, help_text='Free quantity received'),
        ),
    ]
