# Generated by Django 4.2.7 on 2026-03-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '1028_purchasemaster_product_free_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerchallanmaster',
            name='sale_free_qty',
            field=models.FloatField(default=0.0, help_text='Free quantity given'),
        ),
        migrations.AddField(
            model_name='salesmaster',
            name='sale_free_qty',
            field=models.FloatField(default=0.0, help_text='Free quantity given'),
        ),
        migrations.AddField(
            model_name='supplierchallanmaster',
            name='product_free_qty',
            field=models.FloatField(default=0.0, help_text='Free quantity received'),
        ),
        migrations.AddField(
            model_name='supplierchallanmaster2',
            name='product_free_qty',
            field=models.FloatField(default=0.0, help_text='Free quantity received'),
        ),
    ]
