# Generated by Django 4.2.7 on 2026-03-14 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '1034_add_free_qty_to_batch_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchinventorycache',
            name='total_stock',
            field=models.FloatField(default=0, help_text='Total stock (current_stock + current_free_qty)'),
        ),
    ]
