# Generated by Django 4.2.7 on 2026-03-21 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '1035_batchinventorycache_total_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('transaction_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('batch_no', models.CharField(db_index=True, max_length=20)),
                ('expiry_date', models.CharField(help_text='Format: MM-YYYY', max_length=7)),
                ('transaction_type', models.CharField(choices=[('PURCHASE', 'Purchase'), ('SALE', 'Sale'), ('PURCHASE_RETURN', 'Purchase Return'), ('SALES_RETURN', 'Sales Return'), ('SUPPLIER_CHALLAN', 'Supplier Challan'), ('CUSTOMER_CHALLAN', 'Customer Challan'), ('STOCK_ISSUE', 'Stock Issue')], db_index=True, max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Positive for IN, Negative for OUT', max_digits=10)),
                ('free_quantity', models.DecimalField(decimal_places=2, default=0, help_text='Free quantity', max_digits=10)),
                ('transaction_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('reference_type', models.CharField(choices=[('INVOICE', 'Invoice'), ('CHALLAN', 'Challan'), ('ISSUE', 'Stock Issue')], max_length=20)),
                ('reference_id', models.BigIntegerField(help_text='ID of source transaction')),
                ('reference_number', models.CharField(help_text='Invoice/Challan/Issue number', max_length=50)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Purchase/Sale rate per unit', max_digits=10)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_value', models.DecimalField(decimal_places=2, help_text='quantity × rate', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.productmaster')),
            ],
            options={
                'db_table': 'inventory_transaction',
                'ordering': ['-transaction_date', '-transaction_id'],
                'indexes': [models.Index(fields=['product', 'batch_no'], name='idx_inv_product_batch'), models.Index(fields=['transaction_date'], name='idx_inv_date'), models.Index(fields=['transaction_type'], name='idx_inv_type'), models.Index(fields=['product', 'transaction_date'], name='idx_inv_product_date'), models.Index(fields=['reference_type', 'reference_id'], name='idx_inv_reference')],
            },
        ),
    ]
