# Generated by Django 4.2.7 on 2026-03-21 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '1036_add_inventory_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmaster',
            name='product_category',
            field=models.CharField(db_index=True, default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='productmaster',
            name='product_company',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='productmaster',
            name='product_name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='productmaster',
            name='product_salt',
            field=models.CharField(db_index=True, default=None, max_length=300),
        ),
        migrations.AlterField(
            model_name='saleratemaster',
            name='product_batch_no',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['product', 'batch_no', 'expiry_date'], name='idx_inv_prod_batch_exp'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['batch_no', 'expiry_date'], name='idx_inv_batch_expiry'),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['product', 'quantity'], name='idx_inv_product_qty'),
        ),
        migrations.AddIndex(
            model_name='productmaster',
            index=models.Index(fields=['product_name', 'product_company'], name='idx_prod_name_company'),
        ),
        migrations.AddIndex(
            model_name='saleratemaster',
            index=models.Index(fields=['productid', 'product_batch_no'], name='idx_rate_prod_batch'),
        ),
    ]
