# Generated by Django 4.2.7 on 2026-06-09 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '1038_retailer_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailerCSVUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_file', models.FileField(upload_to='retailer_csv_uploads/%Y/%m/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size_kb', models.FloatField(default=0)),
                ('request_type', models.CharField(choices=[('STOCK', 'Stock'), ('PURCHASE', 'Purchase'), ('SALES', 'Sales')], max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('row_count', models.IntegerField(default=0)),
                ('preview_data', models.JSONField(blank=True, null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csv_uploads', to='core.retailerreportrequest')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='csv_uploads', to='core.retailermaster')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
