# Generated by Django 4.2.7 on 2026-06-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '1040_add_retailer_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailersession',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
