# Generated by Django 4.2.7 on 2026-07-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '1041_add_retailer_session_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailercsvupload',
            name='generated_by',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='retailerreportrequest',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='retailercsvupload',
            name='request_type',
            field=models.CharField(choices=[('STOCK', 'Stock'), ('PURCHASE', 'Purchase'), ('SALES', 'Sales'), ('RETURN', 'Return')], max_length=10),
        ),
        migrations.AlterField(
            model_name='retailerreportrequest',
            name='request_type',
            field=models.CharField(choices=[('STOCK', 'Stock'), ('PURCHASE', 'Purchase'), ('SALES', 'Sales'), ('RETURN', 'Return')], max_length=10),
        ),
    ]
