# Generated by Django 4.2.7 on 2026-07-02 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '1042_retailer_error_message_generated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailerreportrequest',
            name='product_ids',
            field=models.TextField(blank=True, default=''),
        ),
    ]
