# Generated by Django 4.2.7 on 2026-08-14 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '1043_retailer_product_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasemaster',
            name='purchase_calculation_mode',
            field=models.CharField(default='flat', max_length=10),
        ),
        migrations.AlterField(
            model_name='salesmaster',
            name='sale_calculation_mode',
            field=models.CharField(default='flat', max_length=10),
        ),
    ]
