# Generated by Django 4.2.7 on 2026-08-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '1044_fix_calculation_mode_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerchallanmaster',
            name='sale_calculation_mode',
            field=models.CharField(default='flat', max_length=10),
        ),
        migrations.AddField(
            model_name='customerchallanmaster2',
            name='sale_calculation_mode',
            field=models.CharField(default='flat', max_length=10),
        ),
    ]
