# Generated by Django 4.2.7 on 2026-08-21 11:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '1045_customerchallanmaster_sale_calculation_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierAdvance',
            fields=[
                ('advance_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('amount', models.FloatField(help_text='Remaining advance balance')),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('payment_mode', models.CharField(default='cash', max_length=50)),
                ('reference_no', models.CharField(blank=True, default='', max_length=50)),
                ('narration', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances', to='core.suppliermaster')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAdvance',
            fields=[
                ('advance_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('amount', models.FloatField(help_text='Remaining advance balance')),
                ('receipt_date', models.DateField(default=django.utils.timezone.now)),
                ('receipt_mode', models.CharField(default='cash', max_length=50)),
                ('reference_no', models.CharField(blank=True, default='', max_length=50)),
                ('narration', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances', to='core.customermaster')),
            ],
        ),
        migrations.CreateModel(
            name='AdvanceLedger',
            fields=[
                ('ledger_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('party_type', models.CharField(choices=[('supplier', 'Supplier'), ('customer', 'Customer')], max_length=10)),
                ('entry_type', models.CharField(choices=[('advance_in', 'Advance Received'), ('adjusted', 'Adjusted Against Invoice')], max_length=20)),
                ('amount', models.FloatField()),
                ('entry_date', models.DateField(default=django.utils.timezone.now)),
                ('invoice_ref', models.CharField(blank=True, default='', help_text='Invoice no if adjusted', max_length=50)),
                ('narration', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.customermaster')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.suppliermaster')),
            ],
            options={
                'ordering': ['-entry_date', '-ledger_id'],
            },
        ),
    ]
