# Generated by Django 4.2.7 on 2026-09-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '1048_add_whole_discount_to_challan1'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerchallan',
            name='whole_discount_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
